### ISSUE TITLE
Conditional expression to handle error cases

### ISSUE THREAD

**Issue by hoangnguyen92dn** [kaungkhantsoe/NimbleTest#6]
I am curious there is a missing `is` on the `ResourceState.NetworkError` branch 😄  So would it be possible to add `is` for consistency to validate the particular type , or do you have any supposed idea to do that?

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/ui/login/LoginActivity.kt#L58-L60

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/ui/home/HomeActivity.kt#L223-L225

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/ui/forget/ForgetPasswordActivity.kt#L57-L59

**Comment by kaungkhantsoe** [comment]
I could add `is` for consistency but `is` works like smart casting and since I don't need to access any variables from it when I get `NetworkError` like `ResourceState.Success` for success data, `ResourceState.Error` and `ResourceState.GenericError` for error message. That's why I didn't add it. 😁Would you like me to make a pull request to add that?

**Comment by hoangnguyen92dn** [comment]
@kaungkhantsoe It's good to make the `when` expression consistent on different branches 😄  Basically, the logic doesn't change so you could leave it as it is for now 🙆‍♂️
